- name: provisionkali
  hosts: localhost
  become: true
  gather_facts: false
  ignore_errors: yes
  tasks:
    - name: Clone my Git provision Kali repository
      git:
        repo: https://github.com/mtrimblett/provisionkali.git
        dest: /opt/provisionkali
        version: main

    - name: Clone my Git Scripts repository
      git:
        repo: https://github.com/mtrimblett/scripts.git
        dest: /opt/scripts
        clone: true
        version: main

    - name: Install xclip package (needed for scripts in my Git repo)
      ansible.builtin.apt:
        name: xclip
        state: present

    - name: Set execute permission
      ansible.builtin.find:
        paths: /opt/scripts
        recurse: no
        file_type: file
      register: script_files

    - name: Set execute permission for each file
      ansible.builtin.file:
        path: "{{ item.path }}"
        mode: a+x
      with_items: "{{ script_files.files }}"

    - name: Clone PimpMyKali repository
      git:
        repo: https://github.com/Dewalt-arch/pimpmykali.git
        dest: /opt/pimpmykali
        version: master

    - name: Clone XenSpawn
      git:
        repo: https://github.com/X0RW3LL/XenSpawn.git
        dest: /opt/XenSpawn
        version: main

    - name: Create /opt/linPEAS directory
      ansible.builtin.file:
        path: /opt/linPEAS
        state: directory

    - name: Create /opt/winPEAS directory
      ansible.builtin.file:
        path: /opt/winPEAS
        state: directory

    - name: Download linpeas.sh
      get_url:
        url: "https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas.sh"
        dest: "/opt/linPEAS/linpeas.sh"

    - name: Download winPEASany.exe
      get_url:
        url: "https://github.com/carlospolop/PEASS-ng/releases/latest/download/winPEASany.exe"
        dest: "/opt/winPEAS/winPEASany.exe"
        
    - name: Download winPEASx64.exe
      get_url:
        url: "https://github.com/carlospolop/PEASS-ng/releases/latest/download/winPEASx64.exe"
        dest: "/opt/winPEAS/winPEASx64.exe"

    - name: Download winPEAS.bat
      get_url:
        url: "https://github.com/carlospolop/PEASS-ng/releases/latest/download/winPEAS.bat"
        dest: "/opt/winPEAS/winPEAS.bat"

    - name: Download winPEASx86.exe
      get_url:
        url: "https://github.com/carlospolop/PEASS-ng/releases/latest/download/winPEASx86.exe"
        dest: "/opt/winPEAS/winPEASx86.exe"

    - name: Create /opt/lse directory
      ansible.builtin.file:
        path: /opt/lse
        state: directory
        
    - name: Download lse
      get_url:
        url: "https://github.com/diego-treitos/linux-smart-enumeration/releases/latest/download/lse.sh"
        dest: "/opt/lse/lse.sh"
        
    - name: Clone adPEAS
      git:
        repo: https://github.com/61106960/adPEAS.git
        dest: /opt/adPEAS
        version: main

    - name: Clone LinEnum
      git:
        repo: https://github.com/rebootuser/LinEnum.git
        dest: /opt/LinEnum
        version: master

    - name: Create /opt/pspy directory
      ansible.builtin.file:
        path: /opt/pspy
        state: directory
        
    - name: Download pspy32
      get_url:
        url: "https://github.com/DominicBreuker/pspy/releases/latest/download/pspy32"
        dest: "/opt/pspy/pspy32"

    - name: Download pspy64
      get_url:
        url: "https://github.com/DominicBreuker/pspy/releases/latest/download/pspy64"
        dest: "/opt/pspy/pspy64"

    - name: Create /opt/PowerView directory
      ansible.builtin.file:
        path: /opt/PowerView
        state: directory

    - name: Download PowerView.ps1
      get_url:
        url: "https://github.com/PowerShellMafia/PowerSploit/blob/dev/Recon/PowerView.ps1"
        dest: "/opt/PowerView/PowerView.ps1"

    - name: Clone PrivescCheck
      git:
        repo: https://github.com/itm4n/PrivescCheck.git
        dest: /opt/PrivescCheck
        version: master

    - name: Create /opt/ligolo-ng directory
      ansible.builtin.file:
        path: /opt/ligolo-ng
        state: directory

    - name: Download ligolo Windows
      get_url:
        url: "https://github.com/nicocha30/ligolo-ng/releases/download/v0.5.1/ligolo-ng_agent_0.5.1_windows_amd64.zip"
        dest: "/opt/ligolo-ng/ligolo-ng_agent_0.5.1_windows_amd64.zip"

    - name: Download ligolo Linux
      get_url:
        url: "https://github.com/nicocha30/ligolo-ng/releases/download/v0.5.1/ligolo-ng_agent_0.5.1_darwin_amd64.tar.gz"
        dest: "/opt/ligolo-ng/ligolo-ng_agent_0.5.1_darwin_amd64.tar.gz"
        
    - name: Install required packages for AutoRecon
      ansible.builtin.apt:
        update_cache: yes
        name:
          - python3
          - python3-pip
          - seclists
          - curl
          - enum4linux
          - feroxbuster
          - gobuster
          - impacket-scripts
          - nbtscan
          - nikto
          - nmap
          - onesixtyone
          - oscanner
          - redis-tools
          - smbclient
          - smbmap
          - snmp
          - sslscan
          - sipvicious
          - tnscmd10g
          - whatweb
          - wkhtmltopdf
          - python3-venv
          - pipx
        state: present


    - name: Install pipx
      ansible.builtin.command:
        cmd: python3 -m pip install --user pipx
      changed_when: false

    - name: Ensure pipx path is set
      ansible.builtin.command:
        cmd: python3 -m pipx ensurepath
      changed_when: false

    - name: Install AutoRecon using pipx
      ansible.builtin.command:
        cmd: pipx install git+https://github.com/Tib3rius/AutoRecon.git
      changed_when: false
